cookie:
  expiry_days: 30
  key: some_random_key
  name: auth_cookie
credentials:
  usernames:
    admin:
      email: admin@example.com
      name: Admin
      password: $2b$12$m5.0LJMO7g8eBB9BHfwHeOQmiu21e4fDRS5DjghumTmXQ9NC8grDK
preauthorized:
- admin@example.com
